name: Sample name
description: Sample description
blank_issues_enabled: true
contact_links:
  - name: Discord Chat
    url: https://chat.bit-country.com
    about: Ask questions and discuss with bit-country's team in real time.
  - name: Questions & Discussions
    url: https://github.com/harrytran998/bit-country/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Donate
    url: https://opencollective.com/bit-country/donate
    about: Love bit-country product? Please consider supporting us via Open Collective.
