name: Update Changelog RC

on:
  push:
    paths:
      - '.changeset/**'
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate the new changelog
        run: pnpm run changelog:gen

      - name: Commit changelog
        run: |
          git add .
          git diff --staged --quiet || git commit -m "docs(changelog): $GITHUB_SHA"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          title: 'docs: update .changelogrc'
          branch: docs/changelog-updates